Readme files for codes without one
shuttle-hq/shuttle-examples pull request #2
Opened 2022-11-18 16:52 UTC by Antonio-dev1

2022-12-06 16:03 UTC, oddgrd reviewed
Hey Antonio, thanks and apologies for the late review! This is a big one, so I think it would be best if we take it in parts. I also think we could make this a bit simpler. For the more complex examples a detailed description is helpful, but I don't think we need to provide so much information for hello worlds. The intent with these examples is to show how users can deploy frameworks with shuttle, we shouldn't really try to teach users how to use the frameworks. The various frameworks have extensive docs and examples for this.

So I would start with just the hello-world examples, they are all one file so it's not very valuable to point out. And their intent is to show how to create a simple app with each framework using shuttle. 

So to sum it up, we should start by focusing on the hello world examples. 
- They should have a header, and then something like: "This example shows you how to create a simple "hello world" application with shuttle and axum. " (with a link to the docs for the framework, like you have already done)
- They have only one file so we can remove the `## Structure` and `## src/lib.rs `parts for these.
- I think we can remove `## Deploy` as well, and instead have `## Run it` explaining how to:
  - Run it locally: `cargo shuttle run`
  - Curl it to test it: `curl localhost:8000/hello`

We might want to add deploy as well, but it will add to the maintenance burden, so we may want to keep that in a central readme instead (or link to the docs). But we can think about that later.

I could have provided a bit more information for this issue before you got started, so don't worry about all these changes. We'll take it one step at a time, starting with the hello-worlds and we'll move on from there.

2023-01-01 17:12 UTC, oddgrd commented
Hey Antonio! It looks like you've implemented my suggestions, but it seems you have pushed your merge commit (https://github.com/shuttle-hq/examples/pull/2/commits/42c6092419ba8c871da75da6d720913d4afed920) without resolving the conflicts. This may be a bit tricky to resolve, but it's a good way to get some experience with git. And trust me when I say everyone gets this wrong a few times before they get it right! :sweat_smile: 

You can read a bit about merge conflicts here: https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts. You should also feel free to reach out in our Discord should you need more help.

The link above uses the command line to resolve conflicts, but if you use VSCode, it may be easier for you to do it graphically. I cloned your branch now, and it looks like you can still resolve the conflicts graphically. Where there are conflicts you need to choose which change to keep, yours or the one coming from the merge. 

So if you open, for example. `poem/hello_world/README.md`, VSCode should show two options, current and incoming. You should choose the one you think is correct, and for poem it would be your most recent change where there is just the intro and instructions for running and curling the example. For some of them you may need to make manual adjustments too, which is fine.

2023-01-04 11:54 UTC, oddgrd commented
I see you pushed another commit to address some conflicts, I'm not sure if you are finished or not, but it's a good idea to communicate back a little bit when you address reviews. It is also important to review your own code, so for example if you view the changed files for this PR in github, there are still some conflicts to resolve. There is also a lot of extra newlines in the READMEs, and some `.idea` files which should not be included.

Again, thanks for working on this, we're getting there!

2023-01-05 21:34 UTC, oddgrd reviewed
Hey Antonio, just some small things left to fix now. :partying_face: I left some comments, pointing out the remaining unresolved conflicts, as well as a couple of comments clarifying what I meant by extra newlines.

2023-01-05 21:34 UTC, oddgrd commented on poem/hello-world/README.md
> +
It's extra newlines like this we should remove, it's correct to have newlines between paragraphs of text, and it's also a good practice to have one newline at the end of every file.

2023-01-05 21:34 UTC, oddgrd commented on poem/todo-mongodb/Cargo.toml
> +>>>>>>> origin/update#1
Here is a conflict that should be resolved.

2023-01-05 21:34 UTC, oddgrd commented on poem/todo-mongodb/README.md
> +
These should be removed too, also from a few of the other readmes.

2023-01-05 21:34 UTC, oddgrd commented on rocket/secrets/README.md
> -
This newline is separating two paragraphs of text, so we should keep it.

2023-01-05 21:34 UTC, oddgrd commented on rocket/todo-postgres/Cargo.toml
> +<<<<<<< HEAD
Another conflict we should resolve here.

2023-01-05 21:34 UTC, oddgrd commented on tide/todo-postgres/Cargo.toml
> +<<<<<<< HEAD
This should be the last unresolved conflict

2023-01-05 21:34 UTC, oddgrd commented on thruster/todo-postgres/Cargo.toml
> +<<<<<<< HEAD
Unresolved conflict here

2023-01-16 07:25 UTC, Antonio-dev1 commented
Hello, I just updated the formatting and removed the extra spaces in the Read Me file

2023-01-18 18:12 UTC, oddgrd commented
> Hello, I just updated the formatting and removed the extra spaces in the Read Me file

Awesome, thanks Antonio! I'm busy with a release this week, but I'll get to this as soon as I can.

2023-02-04 13:31 UTC, oddgrd requested changes
Hey Antonio, sorry it took me so long to get back to this. Hopefully it's not been too long and you're still up to work on this. :slightly_smiling_face: 

There were still some git issues, but I was able to resolve them by fixing the last conflict and merging main. In the future if you're uncertain about how to do something with git, like updating the branch, feel free to reach out to me our on our discord. We're happy to help and git is hard when you're not used to its quirks.

I added some more comments on some small changes we'll need before we can merge this. We've also added some new docs for local runs since we last discussed this PR, and I'm wondering if we should add a link to that rather than the `## Run it` sections. It's here: https://docs.shuttle.rs/introduction/local-run. 

So something like `If you'd like to test your app out locally, check out our [local run](https://docs.shuttle.rs/introduction/local-run) docs.`

2023-02-04 13:31 UTC, oddgrd commented on actix-web/README.md
> -# Actix Web with shuttle
This readme should stay like it was, since it explains some oddities of using actix with shuttle.

2023-02-04 13:31 UTC, oddgrd commented on axum/hello-world/README.md
> +# Hello-World application using Actix
The names are similar, but this is the readme for the axum hello world example, not actix :smile:

2023-02-04 13:31 UTC, oddgrd commented on axum/static-files/README.md
> +This example is inspired by the static-file-server example from the axum repo, to see more ways to do this check out the [original](https://github.com/tokio-rs/axum/blob/main/examples/static-file-ser
We should keep the newline here.
```suggestion

This example is inspired by the static-file-server example from the axum repo, to see more ways to do this check out the [original](https://github.com/tokio-rs/axum/blob/main/examples/static-file-server/src/main.rs).
```

2023-02-04 13:31 UTC, oddgrd commented on axum/websocket/README.md
> +The idea is that the `lib.rs` file handles the client and user and http requests and opens the web sockets.
```suggestion
# Web Sockets with axum 
This example shows how to use axum to develop a web socket [axum](https://docs.rs/axum/0.1.1/axum/ws/index.html) application which we can deploy with shuttle..
```

2023-02-04 13:31 UTC, oddgrd commented on poem/todo-postgres/Cargo.toml
> +shuttle-shared-db = { version = "0.7.2", features = ["postgres"] }
All shuttle crates should be bumped to `0.9.0` now, here and in other `Cargo.toml`s.
```suggestion
shuttle-service = { version = "0.9.0", features = ["web-poem"] }
shuttle-shared-db = { version = "0.9.0", features = ["postgres"] }
```

2023-02-04 13:31 UTC, oddgrd commented on poem/todo-postgres/README.md
> +This app uses the `shuttle service` attribute and `sqlx` to build a database and define its CRUD operations.
This is good, but not completely accurate. We're showing how to develop an application that *uses* a postgres database, we're not developing a database. 
```suggestion
This example shows how to develop a [poem](https://docs.rs/poem/latest/poem/) application with a [Postgres](https://www.postgresql.org/docs/) database, provisioned with shuttle.
```

2023-02-04 13:31 UTC, oddgrd commented on rocket/hello-world/README.md
> +This example shows how to launch a hello world app using the [rocket](https://rocket.rs/v0.4/guide/introduction/) framework and the `#[shuttle_service::main]` attribute.
The current version of rocket is 0.5.0-rc.2, but we can just link to their homepage.
```suggestion
This example shows how to launch a hello world app using [rocket](https://rocket.rs) and shuttle.
```

2023-02-04 13:31 UTC, oddgrd commented on rocket/secrets/README.md
> -
This still needs to be resolved.

2023-02-04 13:31 UTC, oddgrd commented on rocket/todo-postgres/README.md
> +The following example is to present a way to use [rocket](https://rocket.rs/v0.4/guide/introduction/) framework and devlop a relational database for a TODO app using [Postgres](https://www.postgresql
See the review on the poem postgres readme, the same applies here. We should also link to the rocket home page.

2023-02-04 13:31 UTC, oddgrd commented on thruster/todo-postgres/README.md
> +The following example is to present a way to use [thruster](https://docs.rs/thruster/latest/thruster/) framework and devlop a relational database for a TODO app using [Postgres](https://www.postgresq
See review for poem postgres readme, the same applies here.

2023-02-04 13:31 UTC, oddgrd commented on tide/todo-postgres/README.md
> +The following example is to present a way to use [tide](https://docs.rs/tide/latest/tide/) framework and develop a relational database for a TODO app using [Postgres](https://www.postgresql.org/docs/
See review for poem postgres example, same applies here.

2023-02-04 13:31 UTC, oddgrd commented on tower/hello-world/README.md
> +The example is to present a network between client and server using tower
```suggestion
```

2023-02-04 13:31 UTC, oddgrd commented on warp/hello-world/README.md
> +The example is to present an app that uses the warp web framework.
```suggestion
```

2023-08-04 11:10 UTC, closed without merging